import pandas
import streamlit
streamlit.title('A Study Guide for Testers')
streamlit.header('How to improve your Skills')
streamlit.text('For a tester it is very important to stay upto date with the recent')
streamlit.text('technology on the testing and overall on software field.')
streamlit.text('This is because a tester should have different hats')
streamlit.text('It needs to be used as a deveoper or a tester or a dev-ops or')
streamlit.text('an IT staff or a bussiness analyst or maybe a project manager etc.')
streamlit.title('My Parents New Healthy Dinner')
streamlit.header('Breakfast Menu')
streamlit.text('🥣 Omega 3 & Blueberry Oatmeal')
streamlit.text('🥗 Kale, Spinach & Rocket Smoothie')
streamlit.text('🐔 Hard-Boiled Free-Range Egg')
streamlit.text('🥑🍞 Avacado Toast')
streamlit.header('🍌🥭 Build Your Own Fruit Smoothie 🥝🍇')
my_fruit_list = pandas.read_csv("https://uni-lab-files.s3.us-west-2.amazonaws.com/dabw/fruit_macros.txt")
streamlit.dataframe(my_fruit_list)
